name: Test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on:  ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge
        activate-environment: kevlar
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - name: Run all pre-commit checks on the full repo!
      run: |
        pre-commit run --all-files
    - name: Build and install pykevlar
      run: |
        mamba install bazel
        ./generate_bazelrc
        bazel build -c dbg //python:pykevlar_wheel
        pip install --force-reinstall bazel-bin/python/dist/*.whl
    - name: Test
      run: |
        pytest .
