name: Test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on:  ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge
        activate-environment: kevlar
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    - name: Run all pre-commit checks on the full repo!
      run: |
        pre-commit run --all-files
    - name: Install Bazel
      run: |
        sudo apt install apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt update && sudo apt install bazel
    - name: Build and install pykevlar
      run: |
        ./generate_bazelrc
        bazel build -c dbg //python:pykevlar_wheel
        pip install --force-reinstall bazel-bin/python/dist/*.whl
    - name: Test
      run: |
        pytest .
